<!DOCTYPE html>
<html>
<head>
    <title>Inventory Report</title>
    <style>
        @page { size: A4 landscape; margin: 10mm; }
        body { font-family: Arial, sans-serif; font-size: 12px; color: #111827; margin: 0; padding: 0; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #4C7B8F; padding-bottom: 15px; }
        .header h1 { font-size: 20px; margin: 0 0 8px 0; font-weight: bold; }
        .header .meta { font-size: 11px; color: #6b7280; }
        table { width: 100%; border-collapse: collapse; font-size: 10px; page-break-inside: auto; }
        th, td { border: 1px solid #d1d5db; padding: 6px 8px; text-align: left; }
        th { background: #4C7B8F !important; color: white; font-weight: bold; }
        .product-details { margin: 10px 0; padding: 10px; background: #f9fafb; border-radius: 4px; }
        .batches-table { width: 100%; margin: 5px 0; font-size: 9px; }
        .footer { margin-top: 20px; text-align: center; font-size: 10px; color: #6b7280; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Inventory Report</h1>
        <div class="meta">
            Generated: {{ now()->format('M d, Y h:i A') }} | 
            Period: {{ $timePeriod === 'all' ? 'All Time' : ucfirst(str_replace('last', 'Last ', $timePeriod)) }} |
            Total Products: {{ $products->count() }}
        </div>
    </div>

    <!-- Products with Batch Details -->
    @foreach($products as $product)
    <div class="product-details">
        <table>
            <thead>
                <tr>
                    <th>Product Name</th>
                    <th>SKU</th>
                    <th>Brand</th>
                    <th>Category</th>
                    <th>Total Stock</th>
                    <th>Created Date</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ $product->productName }}</td>
                    <td>{{ $product->productSKU ?? 'N/A' }}</td>
                    <td>{{ $product->brand->brandName ?? 'N/A' }}</td>
                    <td>{{ $product->category->categoryName ?? 'N/A' }}</td>
                    <td>{{ $product->batches->sum('quantity') }}</td>
                    <td>{{ \Carbon\Carbon::parse($product->created_at)->format('M d, Y') }}</td>
                </tr>
            </tbody>
        </table>
        
        <!-- Product Batches -->
        <h4 style="margin: 10px 0 5px 0; font-size: 11px;">Batches:</h4>
        <table class="batches-table">
            <thead>
                <tr>
                    <th>Batch Number</th>
                    <th>Quantity</th>
                    <th>Cost Price</th>
                    <th>Expiration Date</th>
                    <th>Purchase Order</th>
                </tr>
            </thead>
            <tbody>
                @foreach($product->batches as $batch)
                <tr>
                    <td>{{ $batch->batch_number ?? 'N/A' }}</td>
                    <td>{{ $batch->quantity }}</td>
                    <td>₱{{ number_format($batch->cost_price, 2) }}</td>
                    <td>{{ $batch->expiration_date ? \Carbon\Carbon::parse($batch->expiration_date)->format('M d, Y') : 'N/A' }}</td>
                    <td>{{ $batch->purchaseOrder->orderNumber ?? 'Manual' }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @endforeach

    <div class="footer">
        Generated by Inventory Management System | Page 1 of 1
    </div>
</body>
</html>