<!DOCTYPE html>
<html>
<head>
    <title>Sales Report</title>
    <style>
        @page { size: A4 landscape; margin: 10mm; }
        body { font-family: Arial, sans-serif; font-size: 12px; color: #111827; margin: 0; padding: 0; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #4C7B8F; padding-bottom: 15px; }
        .header h1 { font-size: 20px; margin: 0 0 8px 0; font-weight: bold; }
        .header .meta { font-size: 11px; color: #6b7280; }
        .stats-container { display: flex; gap: 10px; margin-bottom: 20px; }
        .stat-box { flex: 1; padding: 12px; border-radius: 6px; color: white; text-align: left; }
        .stat-value { font-size: 18px; font-weight: bold; margin: 0; }
        .stat-label { font-size: 11px; margin: 0; opacity: 0.9; }
        table { width: 100%; border-collapse: collapse; font-size: 10px; page-break-inside: auto; }
        th, td { border: 1px solid #d1d5db; padding: 6px 8px; text-align: left; }
        th { background: #4C7B8F !important; color: white; font-weight: bold; }
        .sale-details { margin: 10px 0; padding: 10px; background: #f9fafb; border-radius: 4px; }
        .items-table { width: 100%; margin: 5px 0; font-size: 9px; }
        .footer { margin-top: 20px; text-align: center; font-size: 10px; color: #6b7280; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Sales Report</h1>
        <div class="meta">
            Generated: {{ now()->format('M d, Y h:i A') }} | 
            Period: {{ $timePeriod === 'all' ? 'All Time' : ucfirst(str_replace('last', 'Last ', $timePeriod)) }} |
            Total Sales: {{ $sales->count() }}
        </div>
    </div>
    
    <!-- Stats Summary -->
    <div class="stats-container">
        <div class="stat-box" style="background: #059669;">
            <p class="stat-value">₱{{ number_format($totalRevenue, 2) }}</p>
            <p class="stat-label">Total Revenue</p>
        </div>
        <div class="stat-box" style="background: #dc2626;">
            <p class="stat-value">₱{{ number_format($totalCost, 2) }}</p>
            <p class="stat-label">Total Cost</p>
        </div>
        <div class="stat-box" style="background: {{ $totalProfit >= 0 ? '#059669' : '#dc2626' }};">
            <p class="stat-value">₱{{ number_format($totalProfit, 2) }}</p>
            <p class="stat-label">Total Profit</p>
        </div>
    </div>

    <!-- Sales with Detailed Items -->
    @foreach($sales as $sale)
    <div class="sale-details">
        <table>
            <thead>
                <tr>
                    <th>Invoice #</th>
                    <th>Date</th>
                    <th>Cashier</th>
                    <th>Total Amount</th>
                    <th>Payment Method</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ $sale->invoice_number }}</td>
                    <td>{{ \Carbon\Carbon::parse($sale->sale_date)->format('M d, Y h:i A') }}</td>
                    <td>{{ $sale->user->name ?? 'N/A' }}</td>
                    <td>₱{{ number_format($sale->total_amount, 2) }}</td>
                    <td>{{ $sale->payment_method }}</td>
                </tr>
            </tbody>
        </table>
        
        <!-- Sale Items -->
        <h4 style="margin: 10px 0 5px 0; font-size: 11px;">Items Sold:</h4>
        <table class="items-table">
            <thead>
                <tr>
                    <th>Product</th>
                    <th>Batch</th>
                    <th>Quantity</th>
                    <th>Unit Price</th>
                    <th>Subtotal</th>
                </tr>
            </thead>
            <tbody>
                @foreach($sale->items as $item)
                <tr>
                    <td>{{ $item->product_name }}</td>
                    <td>{{ $item->productBatch->batch_number ?? 'N/A' }}</td>
                    <td>{{ $item->quantity }}</td>
                    <td>₱{{ number_format($item->unit_price, 2) }}</td>
                    <td>₱{{ number_format($item->quantity * $item->unit_price, 2) }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @endforeach

    <div class="footer">
        Generated by Inventory Management System | Page 1 of 1
    </div>
</body>
</html>