<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class PurchaseOrder extends Model
{
    protected $fillable = [
        'orderNumber',
        'supplierId',
        'paymentTerms',
        'deliveryDate',
        'totalAmount',
    ];

    protected static function boot()
    {
        parent::boot();

        static::created(function ($purchaseOrder) {
            // Automatically create a delivery record when a purchase order is created
            $purchaseOrder->deliveries()->create([
                'orderStatus' => 'Pending', // Set default status
                // deliveryId will be automatically generated by the Delivery model's boot method
            ]);
        });
    }

    public function supplier(): BelongsTo
    {
        return $this->belongsTo(Supplier::class, 'supplierId');
    }

    public function items(): HasMany
    {
        return $this->hasMany(PurchaseOrderItem::class);
    }

    public function deliveries(): HasMany
    {
        return $this->hasMany(Delivery::class);
    }
    
    public function badItems()
    {
        return $this->hasManyThrough(BadItem::class, PurchaseOrderItem::class);
    }

    public function notes()
    {
        return $this->hasMany(PONote::class);
    }

    public function productBatches()
    {
        return $this->hasManyThrough(ProductBatch::class, PurchaseOrderItem::class);
    }

    // In PurchaseOrder model - FIX the markAsDelivered method
    public function markAsDelivered()
    {
        // Update the delivery status instead of purchase order status
        $this->deliveries()->update(['orderStatus' => 'Delivered']);
        
        // Just show a toast, no complicated service
        echo "<script>Toast.success('Purchase Order #{$this->id} has been delivered!');</script>";
        
        return $this;
    }

}